services:
  mysql:
    container_name: mysql_calidad
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: javaweb
    volumes:
      - ./deploy/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./deploy/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"

  maven:
    container_name: maven_builder
    image: maven:3.9.4-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./:/app
      - maven_target:/app/target
    command: bash -c "mvn clean install -DskipTests && find /app/target -name '*.war'"
    restart: on-failure

  webapp:
    container_name: webapp_calidad
    image: tomcat:10.1.24-jdk21-temurin-jammy
    depends_on:
      - maven
    volumes:
      - maven_target:/usr/local/tomcat/webapps
    command: bash -c "sleep 15 && cp /usr/local/tomcat/webapps/PaginaWebPoli-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/PaginaWebPoli.war && catalina.sh run"
    ports:
      - "8084:8080"
    restart: always

volumes:
  maven_target: